spring.application.name=school
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.jpa.hibernate.ddl-auto=update

students.avatar.dir.path=avatar
spring.liquibase.change-log=classpath:liquibase/index-practice.yml
logging.level.ru.hogwarts.school.service=DEBUG
logging.level.ru.hogwarts.school.controller=INFO
server.port = 8080